### ISSUE TITLE
Re-upload during the CRL overlap period

### ISSUE THREAD

**Issue by peter-wolfe** [jullienl/HPE-Synergy-OneView-demos#4]
Jullien, 
Nice script. Can you update it to not wait for the CRL expiration. At that point it's too late. Connections will be failing. The script should fetch the CRL before the current one expires - IOW, during the CRL overlap period. The overlap period makes sure that a new CRL is available before the old CRL expires. 
For example:
By default on Active Directory Certificate Services solution, the overlap period is 10% of the CRL lifetime and 12 hours at maximum.
That data was from: https://www.tech-coffee.net/public-key-infrastructure-part-4-configure-certificate-revocation-list/

**Comment by jullienl** [comment]
Thanks Peter for your feedback. 
I'm not sure I understand what they mean by 12 hours at maximum but is it ok if I update the CRLs 12 hours before the CRL expiration date?

**Comment by peter-wolfe** [comment]
Check out
https://blogs.technet.microsoft.com/xdot509/2012/11/26/pki-design-considerations-certificate-revocation-and-crl-publishing-strategies/

and
https://social.technet.microsoft.com/Forums/windowsserver/en-US/954b7758-372e-4c32-a8c5-78ac6cdedd76/crl-overlap-confusion?forum=winserversecurity

which have a better explanation of the overlap and actually debunk the 10% of the CRL period rule.


> but is it ok if I update the CRLs 12 hours before the CRL expiration date?
So the answer is really a function of the when the CA is updating the CRL (e.g.
their overlap window). I don't know if there is an average or a rule of thumb.
You'd determine it by looking the CRL itself to see the update window.
Here's a  CRL example from a google issued cert (www.google.com's<http://www.google.com's> crl):

$ openssl crl -inform DER -in GTSGIAG3.crl -text
Certificate Revocation List (CRL):
        Version 2 (0x1)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: /C=US/O=Google Trust Services/CN=Google Internet Authority G3
        Last Update: Jul 13 01:00:21 2018 GMT
        Next Update: Jul 23 01:00:21 2018 GMT


so basically they have a 10 day validity period. I don't know the point at which the new CRL is available.
I would have guessed at *least* a day earlier.

In principal you could start checking 12 hours in advance but in practice if the network is down/inaccessible or there are other issues that seems too short to me. For a 10 day window I would have started to check a few days in advance.
We can look later in the week to see what  google actually does here.

Another note. VJ noted that to get a CRL for a cert, you have to actually have a cert that is signed by that CA.
So it's not enough to have a CA root, or the intermediate. The leaf certs which are signed by the roots and or intermediates in the trust store, they themselves are not in the trust store. So the script needs a way just
to allow the user to have a static file listing CRL URIs that the user can determine from CAs.
The ones you are finding by default in our trust store are just the intermediates that we are bundling
for HPE Remote Support



--
Peter Wolfe, HPE OneView
Hewlett-Packard Enterprise
+1 404 648 2996
