### ISSUE TITLE
Get-OVIloSso -IloRestSession on powershell linux returns error

### ISSUE THREAD

**Issue by RodrigoEmiliano** [jullienl/HPE-Synergy-OneView-demos#5]
Get-OVServer -ServerName "server.lab" | Get-OVIloSso -IloRestSession

Get-OVIloSso: Exception calling "GetResponse" with "0" argument(s): "The SSL connection could not be established, see inner exception. There is no Runspace available to run scripts in this thread. You can provide one in the DefaultRunspace property of the System.Management.Automation.Runspaces.Runspace type. The script block you attempted to invoke was:  $True "

**Comment by jullienl** [comment]
Which script in my repository does this error refer to?

Check out the following article to see if it can solve your problem: https://www.agilepointnxblog.com/powershell-error-there-is-no-runspace-available-to-run-scripts-in-this-thread/

**Comment by jullienl** [comment]
Closing due to no further activity. This issue can always be re-opened if needed.
